language: php

matrix:
  fast_finish: true
  include:
    - php: '7.1'
      install:
        - composer update
    - php: '7.2'
      install:
        - composer update
    - php: '7.3'
    - php: '7.4'
    - php: 'nightly'
      install:
        - composer install --no-interaction --ignore-platform-reqs
    - php: '7.3'
      name: 'Prefer lowest'
      install:
        - composer install --no-interaction
        - composer update --prefer-lowest
  allow_failures:
    - php: 'nightly'

install:
  composer install --no-interaction

before_script:
 - vendor/bin/phpunit --version
 - mkdir tests/sample_data
 - wget -O tests/sample_data/test.flac http://techslides.com/demos/samples/sample.flac

script:
 - vendor/bin/phpunit

after_script:
  - bash <(curl -s https://codecov.io/bash)

addons:
  apt:
    packages:
      - flac
      - atomicparsley
      - ffmpeg