language: php

php:
  - 7.1
  - 7.2
  - nightly

matrix:
  fast_finish: true

allow_failures:
  - php: nightly

install:
 - composer install --no-interaction
 - composer update

before_script:
 - vendor/bin/phpunit --version

script:
 - vendor/bin/phpunit --bootstrap vendor/autoload.php tests
